# Generated by Django 3.2.18 on 2023-04-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230404_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme_metadata',
            new_name='ThemeMetadata',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
    ]
